### ISSUE TITLE
run requirement.txt file in colab

### ISSUE THREAD

**Issue by dinani65** [nonjosh/conda_env#1]

**Comment by nonjosh** [comment]
Hope your find the answer, feel free to ignore this reply if you got it,  but in case you are still figuring out the problem:

Your file looks like a **conda environment file** instead of **pip requirement file**
It seems to be created by a conda command like `conda list --explicit > spec-file.txt`
To import this conda environment file , you should run `conda install --name myenv --file spec-file.txt` on your development machine which has conda installed
(reference: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html)

But for Colab, probably it will not support conda environment files. Colab is just a gpu instance with python and most common package installed, but it DOES NOT have conda installed. You may create your own `requirement.txt` file (with correct format) for installing your required libraries though
